services:
  - type: web
    name: chatapp
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    branch: main
    region: oregon
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 18 